version: '3.8'

services:
  db:
    image: postgres:15
    container_name: product_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"

  product-service:
    build: ./product-service
    container_name: product_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/products_db
    depends_on:
      - db